[programs.localnet]
fruitbasket = "H5Bzc1FGnatrsFZC18WN1BoKduvwHdTiPuiQWEWv8Pi4"
writer_utils = "FkVPe3KrRE18jXFq4P5CADUSd5YoWiJukBYsxpm2wyB8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/prat/.config/solana/id.json"

[clusters.localnet]
fruitbasket = "H5Bzc1FGnatrsFZC18WN1BoKduvwHdTiPuiQWEWv8Pi4"
writer_utils = "FkVPe3KrRE18jXFq4P5CADUSd5YoWiJukBYsxpm2wyB8"

[[test.genesis]]
address = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"
program = "./deps/serum_dex.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
